apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: openj9
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/watanabesota/openj9
        env:
        - name: TARGET
          value: "openj9 v1"
        ports:
        - containerPort: 9080
        resources:
          limits:
            cpu: "1000m"
