apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: array-init
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: docker.io/watanabesota/array-init-commit
        env:
        - name: CHECKPOINT
          value: "True"
        - name: ARRAY
          value: "100000"
        - name: LOOP
          value: "900000000"
