apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-java-spring
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/watanabesota/helloworld-java-spring
        env:
        - name: TARGET
          value: "Spring Boot Sample v1"
        resources:
          limits:
            cpu: "1000m"
