apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: websocket-chat
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.io/watanabesota/websocket-chat
        env:
        - name: TARGET
          value: "websocket-chat v1"
        resources:
          limits:
            cpu: "1000m"