apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      annotations:
        #autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: watanabesota/helloworld-go
        imagePullPolicy: Never
        env:
        - name: TARGET
          value: "Go Sample v22"
